---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: k3s-clients
  name: k3s-clients
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "update", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "patch", "get", "update", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: k3s-clients-github
  name: k3s-clients-github
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k3s-clients
subjects:
- name: github@default
  kind: User
  apiGroup: rbac.authorization.k8s.io
