---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-standalone2
  volumeMode: Filesystem

