---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-standalone2
  annotations:
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi
