apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uucp
  name: uucp
  namespace: gnuu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: job
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: job
      annotations:
        checksum/secrets: gnuu-secrets | sha256sum
    spec:
      containers:
      - image: gnuu/uucp
        imagePullPolicy: Always
        name: job
        ports:
          - containerPort: 10540
        command: ["sh","-c"]
        args: ["git clone https://github.com/gnuu-de/apps && cd apps/$APP && gunicorn --bind 0.0.0.0:5000 --access-logfile /dev/stdout wsgi:app"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/uucp
          name: gnuu-uucp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gnuu-uucp
          configMap:
            name: gnuu-uucp

