apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-300
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-uucp-300
            image: gnuu/inn
            args:
            - sh
            - -c
            - /entrypoint.sh
            - "&&"
            - /usr/local/bin/send-uucp-gnuu.300
            volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /work-dir
              name: workdir
            - mountPath: /etc/news
              name: all-news
          initContainers:
          - command:
            - bash
            - -x
            - /sidecar/run.sh
            image: gnuu/busybox
            imagePullPolicy: Always
            name: install
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /work-dir
              name: workdir
            - mountPath: /sidecar
              name: news-sidecar
          restartPolicy: OnFailure
          volumes:
          - emptyDir: {}
            name: workdir
          - name: data
            persistentVolumeClaim:
              claimName: data
          - configMap:
              defaultMode: 420
              name: news-sidecar
            name: news-sidecar
          - name: all-news
            projected:
              defaultMode: 420
              sources:
              - configMap:
                  name: gnuu-news
              - configMap:
                  name: news-static
