--
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-300
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-uucp-300
            image: gnuu/inn
            args:
            - sh
            - -c
            - /usr/local/bin/news/send-uucp-gnuu.300
            volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /work-dir
              name: workdir
            - mountPath: /etc/news
              name: all-news
          initContainers:
          - command:
            - bash
            - -x
            - /sidecar/run.sh
            image: gnuu/busybox
            imagePullPolicy: Always
            name: install
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /work-dir
              name: workdir
            - mountPath: /sidecar
              name: news-sidecar
          restartPolicy: OnFailure#
          volumes:
          - emptyDir: {}
            name: workdir
          - name: data
            persistentVolumeClaim:
              claimName: data
          - configMap:
              defaultMode: 420
              name: news-sidecar
            name: news-sidecar
          - name: all-news
            projected:
              defaultMode: 420
              sources:
              - configMap:
                  name: gnuu-news
              - configMap:
                  name: news-static
--
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-1800
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-uucp-1800
            image: gnuu/inn
            args:
            - sh
            - -c
            - /usr/local/bin/news/send-uucp-gnuu.1800
          restartPolicy: OnFailure
--
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-3600
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-uucp-3600
            image: gnuu/inn
            args:
            - sh
            - -c
            - /usr/local/bin/news/send-uucp-gnuu.3600
          restartPolicy: OnFailure
--
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-21600
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-uucp-21600
            image: gnuu/inn
            args:
            - sh
            - -c
            - /usr/local/bin/news/send-uucp-gnuu.21600
          restartPolicy: OnFailure
--
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-43200
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-uucp-43200
            image: gnuu/inn
            args:
            - sh
            - -c
            - /usr/local/bin/news/send-uucp-gnuu.43200
          restartPolicy: OnFailure
--
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-86400
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-uucp-86400
            image: gnuu/inn
            args:
            - sh
            - -c
            - /usr/local/bin/news/send-uucp-gnuu.86400
          restartPolicy: OnFailure
