apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-uucp-300
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
          - name: send-uucp-300
            image: gnuu/innuucp
            command: ["sh","-c"]
            args: ["/entrypoint.sh && /usr/local/bin/send-uucp-gnuu.300"]
            volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /work-dir
              name: workdir
            - mountPath: /etc/news
              name: all-news
            - mountPath: /etc/uucp
              name: gnuu-uucp
          restartPolicy: Never
          volumes:
          - emptyDir: {}
            name: workdir
          - name: data
            persistentVolumeClaim:
              claimName: data
          - configMap:
              defaultMode: 420
              name: news-sidecar
            name: news-sidecar
          - name: all-news
            projected:
              defaultMode: 420
              sources:
              - configMap:
                  name: gnuu-news
              - configMap:
                  name: news-static-cron
          - name: gnuu-uucp
            configMap:
              name: gnuu-uucp
