apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: news
  name: news
  namespace: gnuu
spec:
  serviceName: news
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
      annotations:
        checksum/configmaps: gnuu-news | sha256sum
    spec:
      containers:
      - image: gnuu/innuucp
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        #command: ['sh', '-c']
        #args: ["tail -f /dev/null"]
        name: news
        ports:
          - containerPort: 119
            hostPort: 119
          - containerPort: 540
            hostPort: 540
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data
          mountPath: /data
        - name: newslog
          mountPath: "/newslog"
        - name: workdir
          mountPath: "/work-dir"
        - name: all-news
          mountPath: /etc/news
        - mountPath: /etc/uucp
          name: gnuu-uucp
      - image: gnuu/busybox
        imagePullPolicy: Always
        command: ['sh', '-c']
        args: ['tail -n+1 -f /newslog/news.fifo']
        name: newslog
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: newslog
          mountPath: "/newslog"
      - image: gnuu/busybox
        imagePullPolicy: Always
        command: ['sh', '-c']
        args: ['tail -n+1 -f /data/spool/uucp/Log']
        name: uucplog
        volumeMounts:
        - name: data
          mountPath: /data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      initContainers:
      - name: install
        image: gnuu/busybox
        command: ['bash', '-x', "/sidecar/run.sh"]
        volumeMounts:
        - name: newslog
          mountPath: "/newslog"
        - name: workdir
          mountPath: "/work-dir"
        - name: news-log
          mountPath: /sidecar
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: gnuu-news
      volumes:
      - name: newslog
        emptyDir: {}
      - name: workdir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: news-log
        configMap:
          name: news-log
      - name: all-news
        projected:
          sources:
          - configMap:
              name: gnuu-news
          - configMap:
              name: news-static
      - name: gnuu-uucp
        configMap:
          name: gnuu-uucp
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: gnuu-news
      volumes:
      - name: newslog
        emptyDir: {}
      - name: workdir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: news-log
        configMap:
          name: news-log
      - name: all-news
        projected:
          sources:
          - configMap:
              name: gnuu-news
          - configMap:
              name: news-static
      - name: gnuu-uucp
        configMap:
          name: gnuu-uucp
