apiVersion: v1
data:
  run.sh: |
    s3cmd -v --delete-removed --no-check-md5 --exclude="data/spool/news/*" sync /data s3://gnuubackup && exit 0
kind: ConfigMap
metadata:
  labels:
    app: data-backup
  name: data-backup
