apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    job-name: data-backup
  name: data-backup
spec:
  schedule: "10 23 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: ghcr.io/gnuu-de/busybox:2.0.0
            env:
            - name: COSIGNPUBKEY
              value: |
                  -----BEGIN PUBLIC KEY-----
                  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwT2gClqDPu3VvFfrE56EkW68NXj9
                  Ct5SsvcPZC3yL5+6fa/Ox7isJdsvxf9rRmGKp8slnyN2/aWKIleY3Ut4Hw==
                  -----END PUBLIC KEY-----
            imagePullPolicy: Always
            name: data-backup
            command: ["sh","-c"]
            args: ["/sidecar/run.sh"]
            volumeMounts:
            - name: data
              mountPath: /data
            - name: data-backup
              mountPath: /sidecar
            - name: s3cfg
              readOnly: true
              mountPath: "/root"
          volumes:
          - name: s3cfg
            secret:
              secretName: s3cfg
          - name: data-backup
            configMap:
              defaultMode: 0755
              name: data-backup
          - name: data
            persistentVolumeClaim:
              claimName: data2
