apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    job-name: mysql-backup-gnuu
  name: mysql-backup-gnuu
spec:
  schedule: "00 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: ghcr.io/gnuu-de/busybox:2.0.0
            imagePullPolicy: IfNotPresent
            name: mysql-backup-gnuu
            command: ["sh","-c"]
            #args: ["tail -f /dev/null"]
            args: ["/sidecar/run.sh"]
            env:
            - name: MYSQL_USER
              value: "gnuubackup"
            - name: MYSQL_DB
              value: "gnuu"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gnuu-secrets
                  key: mysql_password
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: gnuu-secrets
                  key: mysql_host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: gnuu-secrets
                  key: mysql_port
            volumeMounts:
            - name: mysql-backup
              mountPath: /sidecar
            - name: s3cfg
              readOnly: true
              mountPath: "/root"
          volumes:
          - name: s3cfg
            secret:
              secretName: s3cfg
          - configMap:
              defaultMode: 0755
              name: mysql-backup
            name: mysql-backup
