---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup-sqlgrey
spec:
  schedule: "32 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup-sqlgrey
            image: gcr.io/maynard-io-public/kubernetes-cloud-mysql-backup
            imagePullPolicy: IfNotPresent
            env:
              - name: AWS_ACCESS_KEY_ID
                value: AHS4H4AXPXBL5V59TUBE
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                   secretKeyRef:
                     name: mysql-backup
                     key: aws_secret_access_key
              - name: AWS_S3_ENDPOINT
                value: "https://s3.hidrive.strato.com"
              - name: AWS_DEFAULT_REGION
                value: "eu-central-1"
              - name: AWS_BUCKET_NAME
                value: "gnuubackup"
              - name: AWS_BUCKET_BACKUP_PATH
                value: "mysql"
              - name: TARGET_DATABASE_HOST
                value: "mysql"
              - name: TARGET_DATABASE_PORT
                value: "3306"
              - name: TARGET_DATABASE_NAMES
                value: "gnuu"
              - name: TARGET_DATABASE_USER
                value: "gnuubackup"
              - name: TARGET_DATABASE_PASSWORD
                valueFrom:
                   secretKeyRef:
                     name: mysql-backup
                     key: database_password
              - name: BACKUP_TIMESTAMP
                value: "_%Y_%m_%d"
              - name: SLACK_ENABLED
                value: "false"
              - name: SLACK_CHANNEL
                value: "#chatops"
          restartPolicy: Never
