apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: s3restorerepo
  name: s3restorerepo
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: gnuu/busybox
        imagePullPolicy: Always
        name: s3restorerepo
        command: ["sh"]
        args: ["-c","s3cmd sync s3://gnuubackup/repo/ /repo/ -v && exit 0"]
        volumeMounts:
        - name: repo
          mountPath: /repo
        - name: s3cfg
          readOnly: true
          mountPath: "/root"
      volumes:
      - name: s3cfg
        secret:
          secretName: s3cfg
      - name: repo
        persistentVolumeClaim:
          claimName: repo
