apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gnuuadm
  name: gnuuadm
spec:
  serviceName: gnuuadm
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gnuuadm
  template:
    metadata:
      labels:
        app: gnuuadm
    spec:
      containers:
      - image: gnuu/busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args: ["tail -f /dev/null"]
        name: gnuuadm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data
          mountPath: /data
        - name: s3cfg
          readOnly: true
          mountPath: "/root"
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: s3cfg
        secret:
          secretName: s3cfg
