apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: newsuucp
  name: newsuucp
spec:
  serviceName: newsuucp
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: newsuucp
  template:
    metadata:
      labels:
        app: newsuucp
      annotations:
        checksum/configmaps: gnuu-news | sha256sum
    spec:
      containers:
      - image: ghcr.io/gnuu-de/innuucp:2.0.0
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        #command: ['sh', '-c']
        #args: ["tail -f /dev/null"]
        name: newsuucp
        ports:
          - containerPort: 119
            hostPort: 119
          - containerPort: 540
            hostPort: 540
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data
          mountPath: /data
        - name: newslog
          mountPath: /newslog
        - name: all-news
          mountPath: /etc/news
        - name: gnuu-uucp
          mountPath: /etc/uucp
        - name: workdir
          mountPath: /work-dir
      - image: ghcr.io/gnuu-de/busybox:2.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args: ['tail -n+1 -f /newslog/news.fifo']
        name: newslog
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: newslog
          mountPath: "/newslog"
      - image: ghcr.io/gnuu-de/busybox:2.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args: ['tail -n+1 -f /data/spool/uucp/Log']
        name: uucplog
        volumeMounts:
        - name: data
          mountPath: /data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      initContainers:
      - name: installmailout
        image: ghcr.io/gnuu-de/busybox:2.0.0
        command: ['bash', '-x', "/sidecar/run.sh"]
        volumeMounts:
        - name: workdir
          mountPath: /work-dir
        - name: mail-out-sidecar
          mountPath: /sidecar
        env:
        - name: mysql_port
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_port
        - name: mysql_db
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_db
        - name: mysql_user
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_user
        - name: mysql_password
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_password
      - name: installlog
        imagePullPolicy: IfNotPresent
        image: ghcr.io/gnuu-de/busybox:2.0.0
        command: ['bash', '-x', "/news-log/run.sh"]
        volumeMounts:
        - name: newslog
          mountPath: /newslog
        - name: news-log
          mountPath: /news-log
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: gnuu-news
      volumes:
      - name: newslog
        emptyDir: {}
      - name: workdir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: news-log
        configMap:
          name: news-log
      - name: all-news
        projected:
          sources:
          - configMap:
              name: gnuu-news
          - configMap:
              name: news-static
      - name: gnuu-uucp
        configMap:
          name: gnuu-uucp
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: gnuu-news
      volumes:
      - name: newslog
        emptyDir: {}
      - name: workdir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: data2
      - name: news-log
        configMap:
          name: news-log
      - name: all-news
        projected:
          sources:
          - configMap:
              name: gnuu-news
          - configMap:
              name: news-static
      - name: gnuu-uucp
        configMap:
          name: gnuu-uucp
      - name: mail-out-sidecar
        configMap:
          name: mail-out-sidecar
