---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: gnuu-monitoring-alertmanager
  name: gnuu-monitoring-alertmanager
  namespace: gnuu
spec:
  baseImage: rancher/prom-alertmanager
  configSecret: alertmanager-gnuu-monitoring-alertmanager
  externalUrl: 'http://gnuu-monitoring-alertmanager.gnuu:9093'
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: web
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: gnuu-monitoring-alertmanager
  version: v0.21.0
