---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: gnuu-monitoring-prometheus
  name: gnuu-monitoring-prometheus
  namespace: gnuu
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: gnuu-monitoring-alertmanager
      namespace: gnuu
      pathPrefix: /
      port: web
  baseImage: rancher/prom-prometheus
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    - -c
    - /nginx/nginx.conf
    image: rancher/library-nginx:1.19.2-alpine
    name: prometheus-proxy
    ports:
    - containerPort: 8080
      name: nginx-http
      protocol: TCP
    securityContext:
      runAsGroup: 101
      runAsUser: 101
    volumeMounts:
    - mountPath: /nginx
      name: prometheus-nginx
    - mountPath: /var/cache/nginx
      name: nginx-home
  enableAdminAPI: false
  evaluationInterval: 1m
  externalUrl: http://gnuu-monitoring-prometheus.gnuu:9090
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: 
    matchLabels:
      gnuu: monitor
  podMonitorSelector: {}
  portName: nginx-http
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2500Mi
    requests:
      cpu: 750m
      memory: 750Mi
  retention: 10d
  retentionSize: 50GiB
  routePrefix: /
  ruleNamespaceSelector:
    matchLabels:
      gnuu: monitor
  ruleSelector: {}
  scrapeInterval: 1m
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: gnuu-monitoring-prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      gnuu: monitor
  serviceMonitorSelector: {}
  version: v2.18.2
  volumes:
  - emptyDir: {}
    name: nginx-home
  - configMap:
      defaultMode: 438
      name: prometheus-nginx-proxy-config
    name: prometheus-nginx
