---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: gnuu-monitoring
    app.kubernetes.io/name: grafana
  name: gnuu-monitoring-grafana
  namespace: gnuu
rules:
- apiGroups:
  - extensions
  resourceNames:
  - rancher-monitoring-grafana
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["get","list","watch"]
