---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: gnuu-monitoring-alertmanager
  name: gnuu-monitoring-alertmanager
  namespace: gnuu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gnuu-monitoring-alertmanager
subjects:
- kind: ServiceAccount
  name: gnuu-monitoring-alertmanager
  namespace: gnuu
