---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gnuu-monitoring-prometheus
  namespace: gnuu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gnuu-monitoring-prometheus
subjects:
- kind: ServiceAccount
  name: gnuu-monitoring-prometheus
  namespace: gnuu
