---
apiVersion: v1
data:
  admin-password: cHJvbS1vcGVyYXRvcg==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: gnuu-monitoring
    app.kubernetes.io/name: grafana
  name: gnuu-monitoring-grafana
  namespace: gnuu
type: Opaque
