---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: riot
  name: riot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot
  strategy: {}
  template:
    metadata:
      labels:
        app: riot
    spec:
      containers:
      - image: vectorim/riot-web
        name: riot
        ports:
          - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
