apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    traefik.backend.loadbalancer.sticky: "true"
    traefik.frontend.passHostHeader: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  name: riot
  namespace: gnuu
spec:
  rules:
  - host: matrix.gnuu.de
    http:
      paths:
      - backend:
          service:
            name: riot
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - matrix.gnuu.de
    secretName: matrix-gnuu-de-cert
