---
kind: Service
apiVersion: v1
metadata:
  name: riot
spec:
  selector:
    app: riot
  ports:
    - port: 80
      targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: matrixbot
spec:
  selector:
    app: matrixbot
  ports:
    - port: 80
      targetPort: 4785

