---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: job
  name: job
  namespace: gnuu
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "delete", "create", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "create", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: job
  name: job
  namespace: gnuu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job
subjects:
  - kind: ServiceAccount
    name: gnuu-job
    namespace: gnuu
