---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: gnuu
  name: gnuu
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.passHostHeader: "true"
    traefik.backend.loadbalancer.sticky: "true"
spec:
  rules:
  - host: k8s.gnuu.de
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
      - path: /cgi-bin/user.cgi
        backend:
          serviceName: app
          servicePort: 80
