---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: gnuu
  name: gnuu
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.passHostHeader: "true"
    traefik.backend.loadbalancer.sticky: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: uucp.gnuu.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /repo
        pathType: Prefix
        backend:
          service:
            name: repo
            port:
              number: 80
      - path: /cgi-bin/
        pathType: Prefix
        backend:
          service:
            name: usr
            port:
              number: 80
      - path: /adm/
        pathType: Prefix
        backend:
          service:
            name: adm
            port:
              number: 80
      - path: /aio/
        pathType: Prefix
        backend:
          service:
            name: aio
            port:
              number: 80
  - host: www.gnuu.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /config
        pathType: Prefix
        backend:
          service:
            name: active
            port:
              number: 80
      - path: /repo
        pathType: Prefix
        backend:
          service:
            name: repo
            port:
              number: 80
      - path: /cgi-bin/
        pathType: Prefix
        backend:
          service:
            name: usr
            port:
              number: 80
      - path: /adm/
        pathType: Prefix
        backend:
          service:
            name: adm
            port:
              number: 80
      - path: /aio/
        pathType: Prefix
        backend:
          service:
            name: aio
            port:
              number: 80
  tls:
  - hosts:
    - uucp.gnuu.de
    - www.gnuu.de
    secretName: www-gnuu-de-cert
