---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: gnuu
  name: gnuu
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.passHostHeader: "true"
    traefik.backend.loadbalancer.sticky: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: uucp.gnuu.de
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
      - path: /repo
        backend:
          serviceName: repo
          servicePort: 80
      - path: /cgi-bin/
        backend:
          serviceName: usr
          servicePort: 80
      - path: /adm/
        backend:
          serviceName: adm
          servicePort: 80
      - path: /aio/
        backend:
          serviceName: aio
          servicePort: 80
  - host: www.gnuu.de
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
      - path: /config
        backend:
          serviceName: active
          servicePort: 80
      - path: /repo
        backend:
          serviceName: repo
          servicePort: 80
      - path: /cgi-bin/
        backend:
          serviceName: usr
          servicePort: 80
      - path: /adm/
        backend:
          serviceName: adm
          servicePort: 80
      - path: /aio/
        backend:
          serviceName: aio
          servicePort: 80
  tls:
  - hosts:
    - uucp.gnuu.de
    - www.gnuu.de
    secretName: www-gnuu-de-cert
