apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: active
  name: active
  namespace: gnuu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: active
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: active
    spec:
      containers:
      - image: gnuu/nginx
        imagePullPolicy: Always
        name: active
        ports:
          - containerPort: 8080
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: true
        - name: workdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: install
        image: gnuu/busybox
        command:
        - ln 
        - -s
        - /data/news/db/
        - /work-dir/config
        volumeMounts:
        - name: workdir
          mountPath: /work-dir
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: workdir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: data
