apiVersion: v1
data:
  run.sh: |
    git clone https://github.com/gnuu-de/serverconfig.git /work-dir
    sed -i "s/\$mysql_host/$(host mysql.gnuu.svc.cluster.local 10.43.0.10 | awk '{print $4}')/" /work-dir/etc/postfix/relay-mysql.cfg.tpl
    sed -i "s/\$mysql_host/$(host mysql.gnuu.svc.cluster.local 10.43.0.10 | awk '{print $4}')/" /work-dir/etc/postfix/transport-mysql.cfg.tpl
    envsubst < /work-dir/etc/postfix/relay-mysql.cfg.tpl > /work-dir/etc/postfix/relay-mysql.cfg
    envsubst < /work-dir/etc/postfix/transport-mysql.cfg.tpl > /work-dir/etc/postfix/transport-mysql.cfg
    rm -rf /var/spool/bsmtp
    ln -s /data/spool/bsmtp /var/spool/bsmtp
kind: ConfigMap
metadata:
  labels:
    app: mail
  name: mail-sidecar
  namespace: gnuu
