apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqlgrey
  name: sqlgrey
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sqlgrey
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqlgrey
    spec:
      containers:
      - image: ghcr.io/gnuu-de/postfix:2.0.0
        env:
        - name: COSIGNPUBKEY
          value: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwT2gClqDPu3VvFfrE56EkW68NXj9
              Ct5SsvcPZC3yL5+6fa/Ox7isJdsvxf9rRmGKp8slnyN2/aWKIleY3Ut4Hw==
              -----END PUBLIC KEY-----
        imagePullPolicy: Always
        command:
        - /sqlgrey.sh
        #command: ['sh', '-c']
        #args: ["tail -f /dev/null"]
        name: sqlgrey
        ports:
          - containerPort: 2501
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: workdir
          mountPath: /work-dir
      initContainers:
      - name: install
        image: ghcr.io/gnuu-de/busybox:2.0.0
        env:
        - name: COSIGNPUBKEY
          value: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwT2gClqDPu3VvFfrE56EkW68NXj9
              Ct5SsvcPZC3yL5+6fa/Ox7isJdsvxf9rRmGKp8slnyN2/aWKIleY3Ut4Hw==
              -----END PUBLIC KEY-----
        command: ['bash', '-x', "/sidecar/run.sh"]
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
        - name: mail-sidecar
          mountPath: /sidecar
        env:
        - name: mysql_port
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_port
        - name: mysql_db
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_db
        - name: mysql_user
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_user
        - name: mysql_password
          valueFrom:
            secretKeyRef:
              name: gnuu-secrets
              key: mysql_password
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: gnuu-mail
      volumes:
      - name: workdir
        emptyDir: {}
      - name: mail-sidecar
        configMap:
          name: mail-sidecar
