---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: mail
  name: mail
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: mail
  name: mail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mail
subjects:
  - kind: ServiceAccount
    name: gnuu-mail
