# DONT DEPLOY THE SERVICE IF YOU USE HOSTNETWORK AND HOSTPORT IN DEPLOYMENT
#---
kind: Service
apiVersion: v1
metadata:
  name: mail
spec:
  selector:
    app: mail
  ports:
    - port: 25
      targetPort: 25
  externalIPs:
    - 85.214.128.138
