---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnuu-api
data:
  config.py: |
    # env $DOCKERHOOK_TOKEN overrides this.
    APIKEY = 'secret'
    # Add your script using the name of your repository as the key
    HOOKS = {
             'busybox': 'sh /api/busybox.sh',
             'nginx': 'sh /api/nginx.sh',
             'postfix': 'sh /api/postfix.sh',
             'innuucp': 'sh /api/innuucp.sh',
             'gnuuaio': 'sh /api/gnuuaio.sh'
            }
  busybox.sh: |
    curl -d "{\"text\":\"Greetings from Kubernetes! New gnuu/busybox image in place\", \"key\": \"$DOCKERHOOK_TOKEN\", \"room\": \"!kDLIfARrwAWsoJnDIR:matrix.org\"}" "http://matrixbot/"
  nginx.sh: |
    curl -d "{\"text\":\"Greetings from Kubernetes! New Deployment: nginx\", \"key\": \"$DOCKERHOOK_TOKEN\", \"room\": \"!kDLIfARrwAWsoJnDIR:matrix.org\"}" "http://matrixbot/"
    kubectl rollout restart deployment/nginx
  postfix.sh: |
    curl -d "{\"text\":\"Greetings from Kubernetes! New Deployment: postfix\", \"key\": \"$DOCKERHOOK_TOKEN\", \"room\": \"!kDLIfARrwAWsoJnDIR:matrix.org\"}" "http://matrixbot/"
    kubectl rollout restart statefulset/mail
    kubectl rollout restart deployment/sqlgrey
  innuucp.sh: |
    curl -d "{\"text\":\"Greetings from Kubernetes! New Deployment: inn/uucp\", \"key\": \"$DOCKERHOOK_TOKEN\", \"room\": \"!kDLIfARrwAWsoJnDIR:matrix.org\"}" "http://matrixbot/"
    kubectl rollout restart statefulset/newsuucp
  gnuuaio.sh: |
    curl -d "{\"text\":\"Greetings from Kubernetes! New Deployment: aio\", \"key\": \"$DOCKERHOOK_TOKEN\", \"room\": \"!kDLIfARrwAWsoJnDIR:matrix.org\"}" "http://matrixbot/"
    kubectl rollout restart statefulset/aio
