---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnuu-api
data:
  config.py: |
    # env $DOCKERHOOK_TOKEN overrides this.
    APIKEY = 'secret'
    # Add your script using the name of your repository as the key
    HOOKS = {
             'busybox': 'kubectl get deployments',
             'nginx': 'kubectl rollout restart deployment/nginx',
             'postfix': 'kubectl rollout restart statefulset/mail',
             'inn': 'kubectl rollout restart statefulset/news',
             'uucp': 'kubectl rollout restart deployment/uucp'
            }
