---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: api
  name: api
rules:
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["get", "list", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: api
  name: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api
subjects:
  - kind: ServiceAccount
    name: gnuu-api
